### ISSUE TITLE
Resolving parsed json

### ISSUE THREAD

**Issue by hafen** [ropensci/graphql#2]
@schloerke has been doing quite a bit of work on an R graphql package (https://github.com/schloerke/graphqlr/tree/R6).  He had to put this on the backburner because of other commitments, but there's quite a bit of work there that goes beyond parsing json objects with the goal of resolving the response into R-like objects based on the graphql object types and not just a list.  We went through quite a few iterations and a lot of work until we found something we think works well.

The status of the work in its current state is the following:
- [x] Given parsed graphql json list, turn into massive r6 object
- [x] For a given ast definition, make sure all properties follow the definition type
- [ ] Validate a schema
- [ ] Resolve methods

If you'd like to discuss leveraging any of this work, we'd be happy to talk with you.

**Comment by jeroen** [comment]
Ah that's unfortunate I was not aware of that package. 

It looks like currently there is not too much overlap. Our package provides zero-dependency cross-platform C++ bindings, whereas @schloerke seems to have focused on more high-level methods. 

You could consider dropping the C++ code from your package and import `graphql` instead? That way you get rid of some bloat and your package works on all systems.

I have to spend some time studying what `graphqlr` exactly does.

**Comment by schloerke** [comment]
Hi Jeroen,

I'd be happy to walk through the package with you. I still have a lot of
loose ends remaining in the code to remind me of what did/didn't work.

Do you have any free time tomorrow?

Best,
Barret

**Comment by hafen** [comment]
@jeroenooms it would be a good idea to import `graphql`.  I'm curious, however, as to whether any of the additional functionality in @schloerke's package is on the roadmap for what you'd like to accomplish with your package.  In that case, I think we'd be totally happy for any relevant work in @schloerke's package to become part of yours.  Probably worth a discussion.

**Comment by jeroen** [comment]
I don't have big plans for this package myself. The goal was mostly to make the `libgraphqlparser` parser accessible to R users, so that it can be used by high-level packages using GraphQL, such as the one by @schloerke or the [ghql](https://github.com/ropensci/ghql) client that @sckott is working on.

**Comment by hafen** [comment]
This can be closed. FYI @schloerke has put the finishing touches on his package: https://github.com/schloerke/gqlr
