### ISSUE TITLE
New version of libgraphql

### ISSUE THREAD

**Issue by schloerke** [ropensci/graphql#3]
Hello,

Could the libgraphqlparser library please be updated to the latest version? They now support "null" values and some minor fixes for unicode escaping.

Thank you!

- Barret

**Comment by jeroen** [comment]
Fixed @ https://github.com/ropensci/graphql/commit/96ced5035e0782a2a2fca99aabc470752a2b4e77.

**Comment by jeroen** [comment]
Submitted to cran...
