### ISSUE TITLE
Updated libgraphqlparser to include schema parsing

### ISSUE THREAD

**Issue by schloerke** [ropensci/graphql#5]
Hi @jeroenooms,

Could you update to the latest libgraphqlparser? 

It now includes schema parsing. Yay!  

(Major feature pull request that was merged in https://github.com/graphql/libgraphqlparser/pull/45)

Thank you,
Barret

**Comment by schloerke** [comment]
Is there a way to do this on my own to not bother you?  I do not need any of this on cran for a while but do enjoy using your c wrapper to the parser.  I'd be happy to update a local copy, but I can't figure out which files you're copying.

**Comment by jeroen** [comment]
Sure just run cmake in the libgraphqlparser repo and copy the src files into the r pkg

**Comment by jeroen** [comment]
I have updated libgraphqlparser code: https://github.com/ropensci/graphql/commit/18e76b96fe06633327daa43b77f6e6918c869806. Do we need to write additional bindings to support schema parsing or is that covered by the existing `graphql2json`?

**Comment by schloerke** [comment]
Added support for the schema here: #6 

This should cover schema parsing bindings.
