### ISSUE TITLE
submit to cran

### ISSUE THREAD

**Issue by schloerke** [ropensci/graphql#9]
Hi @jeroen ,

I've wrapped up my work on `gqlr`.  Would it be possible to release `graphql` to CRAN? 

Thank you,
Barret

**Comment by jeroen** [comment]
Sure, is there any new features you need?

**Comment by jeroen** [comment]
I'll try to do this tomorrow.

**Comment by schloerke** [comment]
#8 libgraphqlparser added position information

That's the only changes I need.

**Comment by jeroen** [comment]
OK I submitted to CRAN, fingers crossed.

**Comment by jeroen** [comment]
On CRAN now.
